server:
  port: 8999
  tomcat:
    max-threads: 500

spring:
  application:
    name: hadoop

logging:
  level:
    root: info

hadoop:
  hdfs:
    ip: 192.168.2.100
    port: 9000
    userName: root
    pool:
      maxTotal: 20
      maxIdle: 10
      minIdle: 5
      maxWaitMillis: 5000
      testWhileIdle: true